### ISSUE TITLE
Gives Invalid Signature in while calling the getRequestToken() method 

### ISSUE THREAD

**Issue by sivaramsi** [adunkman/node-trello#19]
I just replaced the PLAINTEXT  to HMAC-SHA1 in the trello-oauth.js , it works fine.

**Comment by mrgusev** [comment]
The same occurs for me. Looks like the Trello api requires HMAC-SHA1 signature currently.

**Comment by adunkman** [comment]
Fixed in #20, published as `1.1.2`.
