### ISSUE TITLE
Response is full of symbols

### ISSUE THREAD

**Issue by MikaAK** [adunkman/node-trello#22]
The response to ` Trello.get('/member/me/boards', cb)` is returning weird symbols. I followed the correct steps to get both keys but this is still what I get back
```
|sK�}��F{���@D���P�$0U����]����E��m/��߽������u�����
��0�蕼V������s�7�[y8߳]�	������/e�~���8ˋ?�ԗ����?|������K<�N��7ąo1%��\����8�}g8���=tw֛�U���~5_��tx�y�
A@��.����m�?D��� ```

**Comment by notauid** [comment]
@MikaAK I had the same problem, and it turned out that I was omitting the /1/ from the API protocol as your example does.  When present, the data attribute is an object.

**Comment by MikaAK** [comment]
@notauid good solve! I actually ended up creating my own [node client](https://github.com/MikaAK/trello-node) for trello anyway so I'll close this issue
