### ISSUE TITLE
Seems doesn't work well with React Native, for macOS

### ISSUE THREAD

**Issue by rankun203** [adunkman/node-trello#28]
I'm using node-trello along with https://github.com/ptmt/react-native-macos trying to create something that is really useful to me. But seems it stuck at this point: 

```
Unable to resolve module http from /Users/rankun203/LodeStreams/playground/lst/node_modules/node-trello/lib/node-trello.js: 
Unable to find this module in its module map or any of the node_modules directories under 

/Users/node_modules/http and its parent directories This might be related to https://github.com/facebook/react-native/issues/4968 To resolve try the following: 

1. Clear watchman watches: `watchman watch-del-all`. 
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`. 
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
```

Above message was exactly I got when I try to access [http://localhost:8081/index.macos.bundle?platform=macos&dev=true](http://localhost:8081/index.macos.bundle?platform=macos&dev=true).

**Comment by adunkman** [comment]
Seems to be an issue with React Native. This module requires `http` to make requests to Trello, so you’ll need to figure out how to make that available inside of React Native (I don’t know, I’ve never used the project). 

Good luck! If you figure it out, post it here if you don’t mind — then the next person can easily find it! Thanks!

**Comment by rankun203** [comment]
Yes, I installed a [ReactNative version of `http`](https://www.npmjs.com/package/react-native-http) module and renamed the `react-native-http` directory to `http` to resolved the module (I hope they share the same interfaces...). But there are more modules unable to be resolved. Too many I can't find some ReactNative replacement. So I finally gave up and decide to write the functions myself.
