### ISSUE TITLE
Link in README is broken

### ISSUE THREAD

**Issue by JokeyChen** [adunkman/node-trello#34]
The link of Trello public API board is broken: 
https://trello.com/board/trello-public-api/4ed7e27fe6abb2517a21383d
After digging in Trello's team page, I can't seem to find the correct link for the board. Maybe remove it altogether?

**Comment by adunkman** [comment]
Hm, maybe they stopped planning in public! Mind submitting a PR to remove the link?

**Comment by adunkman** [comment]
Fixed in #35! Thanks!
